#!/bin/bash

echo "ZeroDownTimeDeploy TEST"


sudo docker-compose down

sudo docker rmi $(sudo docker images -q)

sudo docker build -t django-sim:1.1.1 .

sudo docker build -t django-sim2:1.1.2 . -f Dockerfile2

sudo docker-compose up -d
